apiVersion: v1
kind: Service
metadata:
  name: {{ include "rocketmq.fullname" . }}-namesrv-hl
  namespace: {{ .Release.Namespace }}
  labels:
    app: namesrv
    app.kubernetes.io/component: namesrv
    app.kubernetes.io/name: {{ include "rocketmq.name" . }}
    helm.sh/chart: {{ include "rocketmq.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  sessionAffinity: None
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: 9876
      targetPort: 9876
      protocol: TCP
      name: rocketmq
  selector:
    app: namesrv
    app.kubernetes.io/component: namesrv
    app.kubernetes.io/name: {{ include "rocketmq.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rocketmq.fullname" . }}-dashboard-hl
  namespace: {{ .Release.Namespace }}
  labels:
    app: dashboard
    app.kubernetes.io/component: dashboard
    app.kubernetes.io/name: {{ include "rocketmq.name" . }}
    helm.sh/chart: {{ include "rocketmq.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  sessionAffinity: None
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: dashboard
  selector:
    app: dashboard
    app.kubernetes.io/component: dashboard
    app.kubernetes.io/name: {{ include "rocketmq.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rocketmq.fullname" . }}-broker-a-hl
  namespace: {{ .Release.Namespace }}
  labels:
    app: broker-a-hl
    app.kubernetes.io/component: broker-a-hl
    app.kubernetes.io/name: {{ include "rocketmq.name" . }}
    helm.sh/chart: {{ include "rocketmq.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  sessionAffinity: None
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: 10911
      targetPort: 10911
      protocol: TCP
      name: broker-a
  selector:
    app: broker-a
    app.kubernetes.io/component: broker-a
    app.kubernetes.io/name: {{ include "rocketmq.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
